#! /bin/bash



# cerr<<"\t1st - scenarionum (1-Renewable, long, 2-Dispatchable, short)"<<endl;
# cerr<<"\t2nd - switchnum (MSB = activeLosses, middle = VSI, LSB = Voltage deviation)"<<endl;
# cerr<<"\t3rd - load_flow_type 1 - const power, 2 - const current"<<endl;
# cerr<<"\t4th - is the first branch a reg transformator? (0-no, 1-yes)"<<endl;
# cerr<<"Next arguments are only used, when scenarionum == 2"<<endl;
# cerr<<"\t5th - Num of DGs"<<endl;
# cerr<<"\t6th - Type of DGs (1 - only P, 2 - only Q, 3 P,Q)"<<endl;


scenarionum=2
num=0
for switchnum in 6
do
	for loadflow in 1 2
	do
		for tr in 0 1
		do
			for dgType in {1..3}
			do
				for  dgNum in {1..3}
				do
					./MOPSO-CP $scenarionum $switchnum $loadflow $tr $dgNum $dgType  
				done
			done
		done 
	done
done
